export const IPC = {
  settingsGet: "settings:get",
  settingsUpdate: "settings:update",
  capabilitiesGet: "capabilities:get",
  financeSnapshot: "finance:snapshot",
  financeCreateWorkbook: "finance:create-workbook",
  financeOpenWorkbook: "finance:open-workbook",
  financeExecute: "finance:execute",
  financeRollover: "finance:rollover",
  financeRevealWorkbook: "finance:reveal-workbook",
  financeRecoverStaleLock: "finance:recover-stale-lock",
  importTemplateGenerate: "import-template:generate",
  importPreview: "import:preview",
  importConfirm: "import:confirm",
  importDiscard: "import:discard",
} as const;
