import { z } from "zod";

const reportOwnerName = z.string().trim().min(1).max(120);

export const propertyReportRequestSchema = z.object({
  propertyId: z.string().uuid(),
  scope: z.enum(["current-year", "lifetime"]),
  language: z.enum(["it", "en"]),
  action: z.enum(["save-pdf", "print"]),
  ownerName: reportOwnerName,
  coOwnerName: reportOwnerName,
}).strict();

export type PropertyReportRequest = z.infer<typeof propertyReportRequestSchema>;

export interface PropertyReportResult {
  canceled: boolean;
  fileName?: string;
}

export const propertyReportTranslations = {
  it: {
    propertyReport: "Report immobile",
    propertyReportDescription: "Crea un resoconto per i proprietari usando soltanto i dati locali del workbook.",
    propertyReportScope: "Periodo del report",
    propertyReportCurrentYear: "Anno corrente",
    propertyReportLifetime: "Intera storia",
    propertyReportOwnerName: "Nome proprietario",
    propertyReportCoOwnerName: "Nome comproprietario",
    propertyReportOwnerNamesHelp: "I nomi compaiono soltanto nel documento e non vengono salvati nel workbook.",
    propertyReportSavePdf: "Salva PDF",
    propertyReportPrint: "Stampa",
    propertyReportGenerating: "Preparazione del report…",
    propertyReportSaved: "Report salvato come {fileName}.",
    propertyReportPrintOpened: "Report inviato al dialogo di stampa.",
    propertyReportError: "Non è stato possibile creare il report. Nessun dato è stato modificato.",
    propertyReportTitle: "Resoconto immobile",
    propertyReportGeneratedOn: "Generato il",
    propertyReportAsOf: "Dati aggiornati al",
    propertyReportPeriod: "Periodo",
    propertyReportProperty: "Immobile",
    propertyReportAddress: "Indirizzo",
    propertyReportArea: "Superficie",
    propertyReportOwnership: "Quote di proprietà",
    propertyReportExecutiveSummary: "Sintesi economica",
    propertyReportActualIncome: "Entrate consuntive",
    propertyReportActualExpenses: "Spese consuntive",
    propertyReportForecastExpenses: "Spese previste fino a fine anno",
    propertyReportProjectedExpenses: "Spese totali proiettate",
    propertyReportCurrentMarketValue: "Valore di mercato corrente",
    propertyReportOwnerAllocation: "Ripartizione per proprietario",
    propertyReportOwner: "Proprietario",
    propertyReportShare: "Quota",
    propertyReportMarketValueShare: "Quota valore di mercato",
    propertyReportIncomeExpenses: "Entrate e uscite per periodo",
    propertyReportCostTrend: "Andamento dei costi negli anni",
    propertyReportCondominium: "Movimenti e costi di condominio",
    propertyReportUtilities: "Utenze: costi e consumi",
    propertyReportForecast: "Spese previste dalla data odierna a fine anno",
    propertyReportMarketHistory: "Valore dell’immobile sul mercato",
    propertyReportMovements: "Dettaglio dei movimenti economici",
    propertyReportMonth: "Mese",
    propertyReportYear: "Anno",
    propertyReportIncome: "Entrate",
    propertyReportExpenses: "Uscite",
    propertyReportNet: "Saldo",
    propertyReportCondominiumCost: "Condominio",
    propertyReportElectricity: "Elettricità",
    propertyReportGas: "Gas",
    propertyReportWater: "Acqua",
    propertyReportPhoneInternet: "Telefono / Internet",
    propertyReportCost: "Costo",
    propertyReportConsumption: "Consumo",
    propertyReportMarketValue: "Valore di mercato",
    propertyReportDate: "Data",
    propertyReportDueDate: "Scadenza",
    propertyReportDescriptionLabel: "Descrizione",
    propertyReportCategory: "Categoria",
    propertyReportType: "Tipo",
    propertyReportAmount: "Importo",
    propertyReportNoData: "Nessun dato disponibile per questa sezione.",
    propertyReportHistoricalNote: "Gli anni archiviati usano i consuntivi annuali conservati nel workbook; le righe puntuali sono mostrate soltanto quando ancora disponibili.",
    propertyReportForecastNote: "Le previsioni includono soltanto uscite pianificate collegate all’immobile e non sono spese già sostenute.",
    propertyReportValueNote: "Il valore mensile riporta l’ultima valutazione disponibile a fine mese; i mesi futuri non vengono stimati.",
    propertyReportTruncated: "Sono mostrate le prime {shown} di {total} righe. I totali includono comunque tutte le registrazioni.",
    propertyReportActual: "Consuntivo",
    propertyReportForecastShort: "Previsto",
    propertyReportProjected: "Proiettato",
    propertyReportAggregate: "Consuntivo annuale",
    propertyReportIncomeType: "Entrata",
    propertyReportExpenseType: "Uscita",
    propertyReportConfidential: "Documento finanziario locale - condividere con attenzione",
    propertyReportPage: "Pagina",
    propertyReportOf: "di",
  },
  en: {
    propertyReport: "Property report",
    propertyReportDescription: "Create an owner statement using only the workbook’s local data.",
    propertyReportScope: "Report period",
    propertyReportCurrentYear: "Current year",
    propertyReportLifetime: "Full history",
    propertyReportOwnerName: "Owner name",
    propertyReportCoOwnerName: "Co-owner name",
    propertyReportOwnerNamesHelp: "Names appear only in the document and are not saved to the workbook.",
    propertyReportSavePdf: "Save PDF",
    propertyReportPrint: "Print",
    propertyReportGenerating: "Preparing report…",
    propertyReportSaved: "Report saved as {fileName}.",
    propertyReportPrintOpened: "Report sent to the print dialog.",
    propertyReportError: "The report could not be created. No data was changed.",
    propertyReportTitle: "Property statement",
    propertyReportGeneratedOn: "Generated on",
    propertyReportAsOf: "Data as of",
    propertyReportPeriod: "Period",
    propertyReportProperty: "Property",
    propertyReportAddress: "Address",
    propertyReportArea: "Floor area",
    propertyReportOwnership: "Ownership shares",
    propertyReportExecutiveSummary: "Financial summary",
    propertyReportActualIncome: "Actual income",
    propertyReportActualExpenses: "Actual expenses",
    propertyReportForecastExpenses: "Forecast expenses through year-end",
    propertyReportProjectedExpenses: "Projected total expenses",
    propertyReportCurrentMarketValue: "Current market value",
    propertyReportOwnerAllocation: "Allocation by owner",
    propertyReportOwner: "Owner",
    propertyReportShare: "Share",
    propertyReportMarketValueShare: "Market-value share",
    propertyReportIncomeExpenses: "Income and expenses by period",
    propertyReportCostTrend: "Cost trend by year",
    propertyReportCondominium: "Condominium movements and costs",
    propertyReportUtilities: "Utilities: costs and consumption",
    propertyReportForecast: "Forecast expenses from today through year-end",
    propertyReportMarketHistory: "Property market value",
    propertyReportMovements: "Detailed financial movements",
    propertyReportMonth: "Month",
    propertyReportYear: "Year",
    propertyReportIncome: "Income",
    propertyReportExpenses: "Expenses",
    propertyReportNet: "Net",
    propertyReportCondominiumCost: "Condominium",
    propertyReportElectricity: "Electricity",
    propertyReportGas: "Gas",
    propertyReportWater: "Water",
    propertyReportPhoneInternet: "Phone / Internet",
    propertyReportCost: "Cost",
    propertyReportConsumption: "Consumption",
    propertyReportMarketValue: "Market value",
    propertyReportDate: "Date",
    propertyReportDueDate: "Due date",
    propertyReportDescriptionLabel: "Description",
    propertyReportCategory: "Category",
    propertyReportType: "Type",
    propertyReportAmount: "Amount",
    propertyReportNoData: "No data is available for this section.",
    propertyReportHistoricalNote: "Archived years use the annual summaries retained in the workbook; individual rows are shown only while they remain available.",
    propertyReportForecastNote: "The forecast includes only planned expenses linked to this property; these amounts have not yet been incurred.",
    propertyReportValueNote: "Monthly value carries forward the latest valuation available at month-end; future months are not estimated.",
    propertyReportTruncated: "The first {shown} of {total} rows are shown. Totals still include every record.",
    propertyReportActual: "Actual",
    propertyReportForecastShort: "Forecast",
    propertyReportProjected: "Projected",
    propertyReportAggregate: "Annual summary",
    propertyReportIncomeType: "Income",
    propertyReportExpenseType: "Expense",
    propertyReportConfidential: "Local financial document - share with care",
    propertyReportPage: "Page",
    propertyReportOf: "of",
  },
} as const;
